name: 'peter.redmond@checkout.com'
description: 'Github action to run a lighthouse audit'
author: 'peter.redmond@checkout.com'
inputs:
  page-speed-insights-key:
    required: true
    description: 'PageSpeed Insights API key'
  url:
    required: true
    description: 'URL to run lighthouse score against'
runs:
  using: 'node16'
  main: 'dist/index.js'
