name: 'peter.redmond@checkout.com'
description: 'Github action to run a lighthouse audit'
author: 'peter.redmond@checkout.com'
inputs:
  page-speed-insights-key:
    required: true
    description: 'PageSpeed Insights API key'
  url:
    required: true
    description: 'URL to run lighthouse score against'
  report-prefix:
    required: true
    description: 'URL where reports are hosted'
outputs:
  slack-message-payload: 
    description: 'Slack message payload'
runs:
  using: 'node16'
  main: 'dist/index.js'
